from __future__ import annotations

"""MacroNarrative — The canonical structured output of a macro research run.

This is the ONLY contract between the Agent and all presentation layers.
CLI, API, Dashboard, PDF — all consume MacroNarrative, not raw Markdown.

Beta upgrade: ScenarioProbability, ConfidenceLevel, confidence_explanation,
today_key_changes, and full-dimension string analyses.

Design rationale (DDR-003, DDR-010):
    - Future LLM, Template, HTML, PDF renderers all consume this contract.
    - Adding a new presentation format never touches the cognitive pipeline.
    - The Narrative Engine knows nothing about Markdown, HTML, or PDF.
"""

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field

from src.domain.narrative import ConfidenceLevel


# ── Dimension Narrative ─────────────────────────────────────────────────────


class DimensionNarrative(BaseModel):
    """Per-dimension structured narrative.

    Each of the four macro dimensions (liquidity, credit, growth, inflation)
    gets its own structured assessment.
    """

    dimension: str = Field(
        ...,
        description="Dimension name: liquidity | credit | growth | inflation",
    )
    summary: str = Field(
        ...,
        description="One-line assessment for this dimension",
    )
    analysis: str = Field(
        default="",
        description="Full analysis text for this dimension (Beta upgrade)",
    )
    key_signals: list[str] = Field(
        default_factory=list,
        description="Key signal descriptions discovered for this dimension",
    )
    hypothesis_summary: str = Field(
        default="",
        description="Summary of relevant hypothesis for this dimension",
    )
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in this dimension's assessment (0-1)",
    )


# ── Scenario Probability ────────────────────────────────────────────────────


class ScenarioProbability(BaseModel):
    """Beta: Rule-based macro scenario with probability assessment.

    Generated by NarrativeEngine._generate_scenarios() from the cognitive chain.
    Rule-based only — no LLM involvement in Beta phase.
    """

    name: str = Field(
        ...,
        description="Scenario name, e.g. 'Soft Landing', 'Hard Landing', 'Stagflation'",
    )
    probability: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Estimated probability of this scenario (0-1)",
    )
    rationale: str = Field(
        default="",
        description="Evidence-based rationale for this probability estimate",
    )
    supporting_signals: list[str] = Field(
        default_factory=list,
        description="Signals that support this scenario",
    )
    contradicting_signals: list[str] = Field(
        default_factory=list,
        description="Signals that contradict this scenario",
    )
    key_indicators_to_watch: list[str] = Field(
        default_factory=list,
        description="Which indicators would confirm or refute this scenario",
    )


# ── Belief Change Note ──────────────────────────────────────────────────────


class BeliefChangeNote(BaseModel):
    """A detected change in belief compared to prior memory.

    Beta upgrade: enhanced with prior_summary for richer visualization.
    """

    hypothesis_statement: str = Field(
        ...,
        description="The hypothesis statement that changed",
    )
    previous_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence in the prior cycle",
    )
    current_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence in the current cycle",
    )
    direction: str = Field(
        ...,
        description="new | increased | decreased | unchanged | reversed",
    )
    note: str = Field(
        default="",
        description="Human-readable explanation of the change",
    )
    prior_summary: str = Field(
        default="",
        description="Prior belief summary for before/after comparison (Beta)",
    )
    dimension: str = Field(
        default="",
        description="Macro dimension this belief belongs to",
    )


# ── Risk Item ───────────────────────────────────────────────────────────────


class RiskItem(BaseModel):
    """A risk identified during the analysis."""

    category: str = Field(
        ...,
        description="Risk category identifier (e.g., 'liquidity_tightening')",
    )
    description: str = Field(
        ...,
        description="Human-readable risk description",
    )
    severity: str = Field(
        default="medium",
        description="low | medium | high | critical",
    )
    related_hypothesis: Optional[str] = Field(
        default=None,
        description="Hypothesis ID this risk relates to",
    )


# ── Confidence Explanation ──────────────────────────────────────────────────


class ConfidenceExplanation(BaseModel):
    """Beta: Detailed breakdown of why the overall confidence is what it is.

    Derived entirely from Reflection findings — never re-reasons.
    """

    level: ConfidenceLevel = Field(
        default=ConfidenceLevel.LOW,
        description="Human-readable tier: HIGH | MEDIUM | LOW",
    )
    score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Numeric confidence score (0-1)",
    )
    why_low: str = Field(
        default="",
        description="Explanation if confidence is LOW — what's missing or uncertain",
    )
    supporting_evidence_summary: str = Field(
        default="",
        description="Summary of evidence that supports the dominant view",
    )
    contradicting_evidence_summary: str = Field(
        default="",
        description="Summary of evidence that contradicts the dominant view",
    )
    reflection_findings_summary: str = Field(
        default="",
        description="Key findings from Reflection that influenced confidence",
    )
    hypothesis_verdict_breakdown: dict = Field(
        default_factory=dict,
        description="Counts: {confirmed: N, refuted: N, uncertain: N}",
    )


# ── MacroNarrative ──────────────────────────────────────────────────────────


class MacroNarrative(BaseModel):
    """The canonical structured output of a macro research run.

    Beta upgrade: ScenarioProbability, confidence_explanation, today_key_changes,
    and rich dimension analysis text.

    This is the ONLY contract between the Agent and all presentation layers.
    CLI, API, Dashboard, PDF — all consume MacroNarrative, not raw Markdown.
    """

    # ── Core ───────────────────────────────────────────────────────────

    summary: str = Field(
        default="",
        description="One-line macro assessment",
    )
    macro_story: str = Field(
        default="",
        description="Macro narrative (2-3 paragraphs of structured text)",
    )
    today_key_changes: str = Field(
        default="",
        description="Beta: What changed today, why it matters, what to watch",
    )

    # ── Dimension Analysis ─────────────────────────────────────────────

    liquidity: DimensionNarrative = Field(
        default_factory=lambda: DimensionNarrative(dimension="liquidity", summary="No liquidity analysis available."),
        description="Liquidity dimension assessment",
    )
    credit: DimensionNarrative = Field(
        default_factory=lambda: DimensionNarrative(dimension="credit", summary="No credit analysis available."),
        description="Credit dimension assessment",
    )
    growth: DimensionNarrative = Field(
        default_factory=lambda: DimensionNarrative(dimension="growth", summary="No growth analysis available."),
        description="Growth dimension assessment",
    )
    inflation: DimensionNarrative = Field(
        default_factory=lambda: DimensionNarrative(dimension="inflation", summary="No inflation analysis available."),
        description="Inflation dimension assessment",
    )

    # ── String Analysis (Beta: flat text for renderers) ────────────────

    liquidity_analysis: str = Field(
        default="",
        description="Full liquidity analysis text (Beta)",
    )
    credit_analysis: str = Field(
        default="",
        description="Full credit analysis text (Beta)",
    )
    growth_analysis: str = Field(
        default="",
        description="Full growth analysis text (Beta)",
    )
    inflation_analysis: str = Field(
        default="",
        description="Full inflation analysis text (Beta)",
    )
    risk_appetite_analysis: str = Field(
        default="",
        description="Risk appetite assessment text (Beta)",
    )

    # ── Scenario Analysis ──────────────────────────────────────────────

    scenario_analysis: list[ScenarioProbability] = Field(
        default_factory=list,
        description="Beta: Rule-based scenario probability assessments",
    )

    # ── Belief Changes ─────────────────────────────────────────────────

    belief_changes: list[BeliefChangeNote] = Field(
        default_factory=list,
        description="Detected belief changes compared to prior memory",
    )
    belief_changes_text: str = Field(
        default="",
        description="Formatted belief changes for display (Beta)",
    )

    # ── Risks ──────────────────────────────────────────────────────────

    risks: list[RiskItem] = Field(
        default_factory=list,
        description="Identified risks and considerations",
    )
    key_risks: list[str] = Field(
        default_factory=list,
        description="Flat list of key risk descriptions (Beta)",
    )

    # ── Action Items ───────────────────────────────────────────────────

    action_items: list[str] = Field(
        default_factory=list,
        description="Items to watch or act upon",
    )

    # ── Confidence ─────────────────────────────────────────────────────

    confidence_level: ConfidenceLevel = Field(
        default=ConfidenceLevel.LOW,
        description="Human-readable confidence tier (Beta)",
    )
    confidence_score: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Numeric confidence score 0-1 (Beta)",
    )
    confidence_explanation: Optional[ConfidenceExplanation] = Field(
        default=None,
        description="Detailed confidence breakdown (Beta)",
    )

    # ── v2.0: Extensible metadata ──────────────────────────────────────

    metadata: dict = Field(
        default_factory=dict,
        description="v2.0: Structured metadata (learning_summary, calibrated_confidence, etc.)",
    )

    # ── Legacy compatibility ───────────────────────────────────────────

    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Overall confidence (legacy — use confidence_score going forward)",
    )

    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the narrative was generated",
    )

    def __repr__(self) -> str:
        dims = []
        for d in [self.liquidity, self.credit, self.growth, self.inflation]:
            dims.append(f"{d.dimension}={d.confidence:.0%}")
        return (
            f"<MacroNarrative confidence={self.confidence_score:.0%} "
            f"level={self.confidence_level.value} "
            f"risks={len(self.risks)} scenarios={len(self.scenario_analysis)} "
            f"dims=[{', '.join(dims)}]>"
        )
